### ISSUE TITLE
java.nio.file.FileSystemNotFoundException: Provider "content" not installed when trying to access the Uri of the selected Image

### ISSUE THREAD

**Issue by macshodan** [skiptools/skip-kit#2]
Hi, 

I'm trying to read the file from the Uri returned from the Android media picker because I need to upload the image to a server.

I can receive the uri of the selected image in the picker, the uri is in the format of `content://media/picker_get_content/0/com.android.providers.media.photopicker/media/23 `
and using for example the AsyncImage object I can display it just fine. 

The problem is when I try to copy the image to another location, I've tried using the FileManager to copy the image for example in the tmpDirectory, but I always get the same error: 'java.nio.file.FileSystemNotFoundException: Provider "content" not installed'.

I've understood that on Android the Uri is not the path of the image, but that you need some provider to fetch the content for you, but I have no idea on how to instantiate such provider with Skip.

Any help would be very much appreciated,
thanks in advance.

**Comment by marcprux** [comment]
The `content://media/picker_get_content` is a special URL protocol that doesn't correspond to an actual file on disk, so `FileManager` cannot access it directly. But you can create a Data from it and then save it out to a file, like:

```
let data = try Data(contentsOf: pickerURL) // e.g. content://media/picker_get_content/…
try data.write(to: URL(fileURLWithPath: "save_image.png"))
```

Let us know if that works for you.

**Comment by macshodan** [comment]
Thanks! It worked like a charm!

I struggled to correctly create a destination directory for the files because it didn't have the correct permission, but in the end I was able to create it right, and the file could be read and write.
